apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminder-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reminder-service
  template:
    metadata:
      labels:
        app: reminder-service
    spec:
      containers:
        - name: reminder-service
          image: reminder-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
      volumes:
        - name: reminder-service-storage
          persistentVolumeClaim:
            claimName: reminder-service-pvc
